package io.github.marioshtika.securestorage

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.GeneralSecurityException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM encryption using a non-exportable key held in the Android Keystore.
 * The raw key is never available to this process or persisted anywhere else.
 * No custom cryptography: only the platform JCA/Keystore primitives are used.
 */
class KeystoreCipher(private val alias: String = DEFAULT_ALIAS) {

    private val keyLock = Any()

    /** Encrypts [plainText]. A fresh random IV is generated by the Keystore for every call. */
    fun encrypt(plainText: ByteArray, associatedData: ByteArray): EncryptedPayload {
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
            cipher.updateAAD(associatedData)
            val cipherText = cipher.doFinal(plainText)
            return EncryptedPayload(cipher.iv, cipherText)
        } catch (e: GeneralSecurityException) {
            throw SecureStorageException(SecureStorageException.ENCRYPTION_ERROR, "Failed to encrypt value", e)
        }
    }

    /** Decrypts and authenticates [payload]; throws if the data was tampered with or the key is gone. */
    fun decrypt(payload: EncryptedPayload, associatedData: ByteArray): ByteArray {
        val key = try {
            getExistingKey()
        } catch (e: GeneralSecurityException) {
            throw SecureStorageException(SecureStorageException.KEYSTORE_ERROR, "Failed to access Android Keystore", e)
        } ?: throw SecureStorageException(
            SecureStorageException.DECRYPTION_ERROR,
            "Encryption key is unavailable; the stored value cannot be decrypted",
        )
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(EncryptedPayload.TAG_LENGTH_BYTES * 8, payload.iv))
            cipher.updateAAD(associatedData)
            return cipher.doFinal(payload.cipherText)
        } catch (e: GeneralSecurityException) {
            throw SecureStorageException(SecureStorageException.DECRYPTION_ERROR, "Failed to decrypt value", e)
        }
    }

    /** Whether the Keystore currently holds the key (used by tests). */
    fun hasKey(): Boolean = try {
        getExistingKey() != null
    } catch (e: GeneralSecurityException) {
        false
    }

    /** Deletes the Keystore key. All previously encrypted values become undecryptable. */
    fun deleteKey() {
        synchronized(keyLock) {
            try {
                keyStore().deleteEntry(alias)
            } catch (e: Exception) {
                throw SecureStorageException(SecureStorageException.KEYSTORE_ERROR, "Failed to delete key", e)
            }
        }
    }

    private fun keyStore(): KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    private fun getExistingKey(): SecretKey? = keyStore().getKey(alias, null) as? SecretKey

    private fun getOrCreateKey(): SecretKey {
        try {
            getExistingKey()?.let { return it }
            // Only key creation is serialized; encrypt/decrypt calls run concurrently.
            synchronized(keyLock) {
                getExistingKey()?.let { return it }
                val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
                generator.init(
                    KeyGenParameterSpec.Builder(
                        alias,
                        KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                    )
                        .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                        .setKeySize(256)
                        // Required (default true): the Keystore generates a unique IV per encryption.
                        .setRandomizedEncryptionRequired(true)
                        .build(),
                )
                return generator.generateKey()
            }
        } catch (e: GeneralSecurityException) {
            throw SecureStorageException(SecureStorageException.KEYSTORE_ERROR, "Failed to access Android Keystore", e)
        }
    }

    companion object {
        const val DEFAULT_ALIAS = "capacitor-secure-storage-key"
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
    }
}
